<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta name="DC.Creator" content="sebastian henschel" />
<meta name="DC.Language" content="en" />
<meta name="DC.Rights" content="all rights are in the public domain" />
<meta name="robots" content="follow" />
<meta name="keywords" content="KVorbisComment Ogg Vorbis comment editor kde qt gpl" />
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta name="generator" content="vim" />
<link rel="stylesheet" href="steil.css" type="text/css" />
